name: pubnub_flutter
description: Flutter extensions for PubNub Dart SDK
version: 0.0.1
homepage: https://www.pubnub.com/docs/platform/home

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

scripts:
  test:
    default: flutter test
  validate:
    analysis: flutter analyze
    formatting: flutter format -n --set-exit-if-changed lib

dependencies:
  async: ^2.4.2
  # If this were to be published, then you'd have to publish pubnub dart and then change this to point to the live pubnub dart
  pubnub:
    path: ../pubnub
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter